// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWD0Tu1OTEHnLngR4lxc3YWHOLnmSUK3o',
    appId: '1:304819161897:web:4ab5979ac021d26a200538',
    messagingSenderId: '304819161897',
    projectId: 'flutter-chat-app-lap2025',
    authDomain: 'flutter-chat-app-lap2025.firebaseapp.com',
    storageBucket: 'flutter-chat-app-lap2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkODHtvqvA4PisVUwvg3l3kfKgzuokGqE',
    appId: '1:304819161897:android:65d6ae17c86a6f01200538',
    messagingSenderId: '304819161897',
    projectId: 'flutter-chat-app-lap2025',
    storageBucket: 'flutter-chat-app-lap2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAedOsjkKebmlSNjGnc9w6zEIK07fSORuE',
    appId: '1:304819161897:ios:7438df91a53cf321200538',
    messagingSenderId: '304819161897',
    projectId: 'flutter-chat-app-lap2025',
    storageBucket: 'flutter-chat-app-lap2025.firebasestorage.app',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAedOsjkKebmlSNjGnc9w6zEIK07fSORuE',
    appId: '1:304819161897:ios:7438df91a53cf321200538',
    messagingSenderId: '304819161897',
    projectId: 'flutter-chat-app-lap2025',
    storageBucket: 'flutter-chat-app-lap2025.firebasestorage.app',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWD0Tu1OTEHnLngR4lxc3YWHOLnmSUK3o',
    appId: '1:304819161897:web:4e26dc6407aafa93200538',
    messagingSenderId: '304819161897',
    projectId: 'flutter-chat-app-lap2025',
    authDomain: 'flutter-chat-app-lap2025.firebaseapp.com',
    storageBucket: 'flutter-chat-app-lap2025.firebasestorage.app',
  );
}
